In [3]:
import numpy as np

In [30]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [43]:
def sigmoid_derivate(x):
    return x*(1-x)

In [51]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T

In [153]:
np.random.seed(1)

In [53]:
synaptic_weights = 2* np.random.random((3,1)) - 1

In [54]:
print("random starting synaptic weights")
print(synaptic_weights)

random starting synaptic weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [57]:
for iteration in range(20000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error * sigmoid_derivate(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)
#     synaptic_weights += np.dot(input_layer.T, adjustments)
    
print("synaptic weights after training")
print(synaptic_weights)
    
print("Original training outputs")
print(training_outputs)
print("outputs after training")
print(outputs)

synaptic weights after training
[[11.49345763]
 [-0.2048909 ]
 [-5.54227641]]
Original training outputs
[[0]
 [1]
 [1]
 [0]]
outputs after training
[[0.00390234]
 [0.99681554]
 [0.99740397]
 [0.00318168]]


In [200]:
class MLP:
    def __init__(self, num_inputs=2, num_hidden=[3,4], num_outputs = 2):
        self.num_inputs = num_inputs
        self.num_hidden = num_hidden
        self.num_outputs = num_outputs
        
        layers = [self.num_inputs] + self.num_hidden + [self.num_outputs]
         
        self.weights = []

        for i in range(len(layers)-1):
            w = np.random.rand(layers[i], layers[i+1])
            
            self.weights.append(w)
            
    def forward_propagate(self, inputs):
        activations = inputs 
         
        for w in self.weights:
            net_inputs = np.dot(activations, w)
            
            activations = self.sigmoid(net_inputs)
            
        return activations
            
    def sigmoid(self, x):
        return 1/(1+ np.exp(-x))

In [201]:
np.random.seed(1)

mlp = MLP()
inputs = np.random.rand(mlp.num_inputs)
outputs = mlp.forward_propagate(inputs)
print(outputs)

[0.81517784 0.86832732]
