In [32]:
import numpy as np

In [33]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [34]:
def sigmoid_derivate(x):
    return x*(1-x)

In [35]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T

In [36]:
np.random.seed(1)

In [37]:
synaptic_weights = 2* np.random.random((3,1)) - 1

In [38]:
print("random starting synaptic weights")
print(synaptic_weights)

random starting synaptic weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [39]:
for iteration in range(20000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - outputs
    adjustments = error * sigmoid_derivate(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

    
print("synaptic weights after training")
print(synaptic_weights)
    
print("Original training outputs")
print(training_outputs)
print("outputs after training")
print(outputs)

synaptic weights after training
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Original training outputs
[[0]
 [1]
 [1]
 [0]]
outputs after training
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]


In [40]:
class MLP:
    def __init__(self, num_inputs=2, num_hidden=[3,4], num_outputs = 2):
        self.num_inputs = num_inputs
        self.num_hidden = num_hidden
        self.num_outputs = num_outputs
        
        layers = [self.num_inputs] + self.num_hidden + [self.num_outputs]
         
        weights = [] 
        for i in range(len(layers)-1):
            w = np.random.rand(layers[i], layers[i+1])
            weights.append(w)
        self.weights = weights
        
        activations = []
        for i in range(len(layers)):
            a = np.zeros(layers[i])
            activations.append(a)
        self.activations = activations
        
        derivatives = [] 
        for i in range(len(layers)-1):
            d = np.random.rand(layers[i], layers[i+1])
            derivatives.append(w)
        self.derivatives = derivatives
            
    def forward_propagate(self, inputs):
        activations = inputs  
        
        self.activations[0] = inputs
        
        for i, w in enumerate(self.weights):
            net_inputs = np.dot(activations, w) 
             
            activations = self.sigmoid(net_inputs)
            
            self.activations[i+1] = activations
            
        return activations
    
    def back_propagate(self, error):
        for i in reverse(range(len(self.derivatives))):
            print(i)
        
    def sigmoid(self, x):
        return 1/(1+ np.exp(-x))
    
    
    

In [43]:
np.random.seed(1)

mlp = MLP() 
inputs = np.random.rand(mlp.num_inputs)
outputs = mlp.forward_propagate(inputs)
print(outputs)


[0.81755214 0.87051793]
