In [ ]:
# conda install pytorch -c pytorch
# conda list pytorch

In [36]:
import torch
import numpy as np

In [3]:
print(torch.__version__)

1.5.0


In [4]:
torch.cuda.is_available()

False

In [24]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [25]:
if torch.cuda.is_available():
    t = t.cuda()
    print(t)
else:
    print("No CUDA")

No CUDA


In [28]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [29]:
t = torch.Tensor()
type(t)
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [34]:
torch.get_default_dtype()

torch.float32

In [31]:
torch.tensor([1,2,4])

tensor([1, 2, 4])

In [32]:
torch.tensor([1.,.3,.4])

tensor([1.0000, 0.3000, 0.4000])

In [37]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3])

In [38]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [39]:
t.shape

torch.Size([3])

In [40]:
len(t.shape)

1

In [48]:
t1= t.reshape(1,3)
print(t1.shape)
t1

torch.Size([1, 3])


tensor([[1, 2, 3]])

In [49]:
t2= t.reshape(1,3).squeeze()
print(t2.shape)
t2

torch.Size([3])


tensor([1, 2, 3])

In [50]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeze()
    return t

In [58]:
t.reshape(1,3)

tensor([[1, 2, 3]])

In [59]:
t.reshape(-1)

tensor([1, 2, 3])

In [60]:
t1 = torch.tensor([[1,2], [3,4]])
t1

tensor([[1, 2],
        [3, 4]])

In [61]:
t2 = torch.tensor([[5,6],[7,8]])
t2

tensor([[5, 6],
        [7, 8]])

In [62]:
vstack = torch.cat((t1,t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [63]:
torch.cat((t1,t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])